
package br.com.fiap.fornecedor.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FornecedorException", targetNamespace = "http://ws.fornecedor.fiap.com.br/")
public class FornecedorException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FornecedorException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FornecedorException_Exception(String message, FornecedorException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FornecedorException_Exception(String message, FornecedorException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.fiap.fornecedor.ws.FornecedorException
     */
    public FornecedorException getFaultInfo() {
        return faultInfo;
    }

}
