
package br.com.fiap.fornecedor.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FornecedorWSService", targetNamespace = "http://ws.fornecedor.fiap.com.br/", wsdlLocation = "http://54.161.101.155/Fornecedor/FornecedorWS?wsdl")
public class FornecedorWSService
    extends Service
{

    private final static URL FORNECEDORWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException FORNECEDORWSSERVICE_EXCEPTION;
    private final static QName FORNECEDORWSSERVICE_QNAME = new QName("http://ws.fornecedor.fiap.com.br/", "FornecedorWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://54.161.101.155/Fornecedor/FornecedorWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FORNECEDORWSSERVICE_WSDL_LOCATION = url;
        FORNECEDORWSSERVICE_EXCEPTION = e;
    }

    public FornecedorWSService() {
        super(__getWsdlLocation(), FORNECEDORWSSERVICE_QNAME);
    }

    public FornecedorWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FORNECEDORWSSERVICE_QNAME, features);
    }

    public FornecedorWSService(URL wsdlLocation) {
        super(wsdlLocation, FORNECEDORWSSERVICE_QNAME);
    }

    public FornecedorWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FORNECEDORWSSERVICE_QNAME, features);
    }

    public FornecedorWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FornecedorWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FornecedorWS
     */
    @WebEndpoint(name = "FornecedorWSPort")
    public FornecedorWS getFornecedorWSPort() {
        return super.getPort(new QName("http://ws.fornecedor.fiap.com.br/", "FornecedorWSPort"), FornecedorWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FornecedorWS
     */
    @WebEndpoint(name = "FornecedorWSPort")
    public FornecedorWS getFornecedorWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.fornecedor.fiap.com.br/", "FornecedorWSPort"), FornecedorWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FORNECEDORWSSERVICE_EXCEPTION!= null) {
            throw FORNECEDORWSSERVICE_EXCEPTION;
        }
        return FORNECEDORWSSERVICE_WSDL_LOCATION;
    }

}
