
package br.com.fiap.fornecedor.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FornecedorWS", targetNamespace = "http://ws.fornecedor.fiap.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FornecedorWS {


    /**
     * 
     * @return
     *     returns java.util.List<br.com.fiap.fornecedor.ws.ProdutoDTO>
     * @throws FornecedorException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarProdutos", targetNamespace = "http://ws.fornecedor.fiap.com.br/", className = "br.com.fiap.fornecedor.ws.ListarProdutos")
    @ResponseWrapper(localName = "listarProdutosResponse", targetNamespace = "http://ws.fornecedor.fiap.com.br/", className = "br.com.fiap.fornecedor.ws.ListarProdutosResponse")
    public List<ProdutoDTO> listarProdutos()
        throws FornecedorException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws FornecedorException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "efetuarPedido", targetNamespace = "http://ws.fornecedor.fiap.com.br/", className = "br.com.fiap.fornecedor.ws.EfetuarPedido")
    @ResponseWrapper(localName = "efetuarPedidoResponse", targetNamespace = "http://ws.fornecedor.fiap.com.br/", className = "br.com.fiap.fornecedor.ws.EfetuarPedidoResponse")
    public boolean efetuarPedido(
        @WebParam(name = "arg0", targetNamespace = "")
        PedidoDTO arg0)
        throws FornecedorException_Exception
    ;

}
